language: python
python: 2.7
branches:
  except:
    - gh-pages
env:
  - TOX_ENV=py27
matrix:
  fast_finish: true
before_install:
  - sudo apt-get -qq update
install:
  - python -m pip install -U pip
  - pip install -U setuptools
  - pip install tox-travis codecov
script:
  - tox
after_success:
  - codecov
