ctl:
  permissions:
    - namespace: "ctl"
      permission: "r"

  plugins:
    - name: this_repo
      type: git
      config:
        repo_url: git@github.com:20c/pytest-filedata.git

    - name: version
      type: semver2
